# Generated by Django 5.0.6 on 2024-06-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicity',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicity',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
