# Generated by Django 5.0.6 on 2024-07-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_suppliment_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='percentage_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
