# Generated by Django 5.0.6 on 2024-07-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_item_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id_returned',
            field=models.IntegerField(default=0),
        ),
    ]
