# Generated by Django 5.0.6 on 2024-07-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_order_order_id_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='percentage',
            field=models.IntegerField(default=15),
        ),
    ]
