# Generated by Django 5.0.6 on 2024-07-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_not_blocked',
            field=models.BooleanField(default=True),
        ),
    ]
